/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package drawdemofrm;

/**
 *
 * @author Verena
 */
public class DrawDemoFrm extends javax.swing.JFrame {


    /**
     * Creates new form DrawDemoFrm
     */
    public DrawDemoFrm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        butGroupFirgure = new javax.swing.ButtonGroup();
        panDraw1 = new drawdemofrm.PanDraw();
        menu = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuOptions = new javax.swing.JMenu();
        menuFigure = new javax.swing.JMenu();
        menuRadButCircle = new javax.swing.JRadioButtonMenuItem();
        menuRadButRe = new javax.swing.JRadioButtonMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout panDraw1Layout = new javax.swing.GroupLayout(panDraw1);
        panDraw1.setLayout(panDraw1Layout);
        panDraw1Layout.setHorizontalGroup(
            panDraw1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        panDraw1Layout.setVerticalGroup(
            panDraw1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        jMenu1.setText("File");
        menu.add(jMenu1);

        menuOptions.setText("Options");

        menuFigure.setText("Figure");

        butGroupFirgure.add(menuRadButCircle);
        menuRadButCircle.setSelected(true);
        menuRadButCircle.setText("Circle");
        menuRadButCircle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuRadButCircleActionPerformed(evt);
            }
        });
        menuFigure.add(menuRadButCircle);

        butGroupFirgure.add(menuRadButRe);
        menuRadButRe.setText("Rectangle");
        menuRadButRe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuRadButReActionPerformed(evt);
            }
        });
        menuFigure.add(menuRadButRe);

        menuOptions.add(menuFigure);

        menu.add(menuOptions);

        setJMenuBar(menu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panDraw1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panDraw1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuRadButCircleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuRadButCircleActionPerformed
        this.panDraw1.changeFigure(PanDraw.CIRCLE);
        System.out.println("circle");
    }//GEN-LAST:event_menuRadButCircleActionPerformed

    private void menuRadButReActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuRadButReActionPerformed
        this.panDraw1.changeFigure(PanDraw.RECTANGLE);
        System.out.println("retangle");
    }//GEN-LAST:event_menuRadButReActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DrawDemoFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DrawDemoFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DrawDemoFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DrawDemoFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DrawDemoFrm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup butGroupFirgure;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar menu;
    private javax.swing.JMenu menuFigure;
    private javax.swing.JMenu menuOptions;
    private javax.swing.JRadioButtonMenuItem menuRadButCircle;
    private javax.swing.JRadioButtonMenuItem menuRadButRe;
    private drawdemofrm.PanDraw panDraw1;
    // End of variables declaration//GEN-END:variables
}
