/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package drawdemofrm;

import java.awt.Color;
import java.awt.Graphics;

/**
 *
 * @author Verena
 */
public class PanDraw extends javax.swing.JPanel {

    Figure c;
    public static int SIZE=40;
    private int x = SIZE/2;
    private int y = SIZE/2;
    public static final int CIRCLE=1;
    public static final int RECTANGLE=2;
    private int figure_type = CIRCLE;
    public FigureManagment fm = new FigureManagment();

    /**
     * Creates new form PanDraw
     */
    public PanDraw() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        if(figure_type == CIRCLE){
            fm.add(new Circle(evt.getX(), evt.getY()));
        }
        if(figure_type == RECTANGLE){
            fm.add(new Rectangle(evt.getX(), evt.getY()));
        }
        repaint();
    }//GEN-LAST:event_formMousePressed

    @Override
    public void paintComponent (Graphics g){
        super.paintComponent(g);
        fm.paint(g);
    }
    
    public void changeFigure(int figure_type){
        this.figure_type = figure_type;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
