/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package dijkstra;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author sebas
 */
public class FrmMain extends javax.swing.JFrame {

    /**
     * Creates new form FrmMain
     */
    public FrmMain() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgItem = new javax.swing.ButtonGroup();
        drawPanal1 = new dijkstra.DrawPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        miSave = new javax.swing.JMenuItem();
        miLoad = new javax.swing.JMenuItem();
        miPaint = new javax.swing.JMenu();
        rbmiPoint = new javax.swing.JRadioButtonMenuItem();
        mTransition = new javax.swing.JMenu();
        rbmiVertical = new javax.swing.JRadioButtonMenuItem();
        rbmiHorizontal = new javax.swing.JRadioButtonMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(600, 600));

        javax.swing.GroupLayout drawPanal1Layout = new javax.swing.GroupLayout(drawPanal1);
        drawPanal1.setLayout(drawPanal1Layout);
        drawPanal1Layout.setHorizontalGroup(
            drawPanal1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        drawPanal1Layout.setVerticalGroup(
            drawPanal1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        jMenu1.setText("File");

        miSave.setText("Save");
        miSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miSaveActionPerformed(evt);
            }
        });
        jMenu1.add(miSave);

        miLoad.setText("Load");
        miLoad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miLoadActionPerformed(evt);
            }
        });
        jMenu1.add(miLoad);

        jMenuBar1.add(jMenu1);

        miPaint.setText("Item");

        bgItem.add(rbmiPoint);
        rbmiPoint.setSelected(true);
        rbmiPoint.setText("Point");
        rbmiPoint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbmiPointActionPerformed(evt);
            }
        });
        miPaint.add(rbmiPoint);

        mTransition.setText("Transition");

        bgItem.add(rbmiVertical);
        rbmiVertical.setText("Vertical");
        rbmiVertical.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbmiVerticalActionPerformed(evt);
            }
        });
        mTransition.add(rbmiVertical);

        bgItem.add(rbmiHorizontal);
        rbmiHorizontal.setText("Horizontal");
        rbmiHorizontal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbmiHorizontalActionPerformed(evt);
            }
        });
        mTransition.add(rbmiHorizontal);

        miPaint.add(mTransition);

        jMenuBar1.add(miPaint);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(drawPanal1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(drawPanal1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void miSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miSaveActionPerformed
        try {
            // TODO add your handling code here:
            drawPanal1.save();
        } catch (IOException ex) {
            Logger.getLogger(FrmMain.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_miSaveActionPerformed

    private void miLoadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miLoadActionPerformed
        // TODO add your handling code here:
        drawPanal1.load();
    }//GEN-LAST:event_miLoadActionPerformed

    private void rbmiPointActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbmiPointActionPerformed
        // TODO add your handling code here:
        if (rbmiPoint.isSelected())
            NodeManagement.selectedItem = 0;
    }//GEN-LAST:event_rbmiPointActionPerformed

    private void rbmiVerticalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbmiVerticalActionPerformed
        // TODO add your handling code here:
        if (rbmiVertical.isSelected())
            NodeManagement.selectedItem = 1;
    }//GEN-LAST:event_rbmiVerticalActionPerformed

    private void rbmiHorizontalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbmiHorizontalActionPerformed
        // TODO add your handling code here:
        if (rbmiHorizontal.isSelected())
            NodeManagement.selectedItem = 2;
    }//GEN-LAST:event_rbmiHorizontalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgItem;
    private dijkstra.DrawPanel drawPanal1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu mTransition;
    private javax.swing.JMenuItem miLoad;
    private javax.swing.JMenu miPaint;
    private javax.swing.JMenuItem miSave;
    private javax.swing.JRadioButtonMenuItem rbmiHorizontal;
    private javax.swing.JRadioButtonMenuItem rbmiPoint;
    private javax.swing.JRadioButtonMenuItem rbmiVertical;
    // End of variables declaration//GEN-END:variables
}
